FROM golang:1.25-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o payment ./main.go

FROM alpine:latest

WORKDIR /root/
COPY --from=builder /app/payment .

EXPOSE ${PORT}

CMD ["./payment"]