version: "3.9"
services:
  payment:
    build: ./payment
    ports:
      - "8080:8080"
    environment:
      - DB_CONN=postgres://postgres:postgres@dbanking-db:5432/dbanking?sslmode=disable
      - PORT=8080
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - dbanking-db
      - rabbitmq

  dbanking-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbanking
    ports:
      - "5433:5432"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3.12-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  ledger:
    build: ./ledger
    environment:
      - DB_CONN=postgres://postgres:postgres@dbanking-db:5432/dbanking?sslmode=disable
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - dbanking-db
      - rabbitmq

  bank:
    build: ./bank
    environment:
      - DB_CONN=postgres://postgres:postgres@dbanking-db:5432/dbanking?sslmode=disable
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - PAYMENT_SERVICE_ADDR=payment:8080
    depends_on:
      - dbanking-db
      - rabbitmq
      - payment
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  notification:
    build: ./notification
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
    depends_on:
      - rabbitmq
      - mailhog